// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMedsAPI.Data;

#nullable disable

namespace SmartMedsAPI.Migrations
{
    [DbContext(typeof(SmartMedsDbContext))]
    partial class SmartMedsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SmartMedsAPI.Models.Domain.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("badc6845-6d80-4b28-bff6-7d8ddd361fb6"),
                            CreatedAt = new DateTime(2025, 10, 17, 18, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Aspirin",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("fa8aad6a-d93a-4ed3-943c-684502e5ecbf"),
                            CreatedAt = new DateTime(2025, 10, 17, 18, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Ibuprofen",
                            Quantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
